### ISSUE TITLE
vae_model_path and image_encoder_path download issue

### ISSUE THREAD

**Issue by ychenZHANG** [mayuelala/FollowYourEmoji#14]
Awesome work!
Please kindly provide the download links for models designated as  "vae_model_path" and "image_encoder_path"  in the infer.yaml. As when I run the scripts, I met issues when downloading from huggingface.

`
Traceback (most recent call last):
  File "/opt/tiger/tools/sd/follow_emoji/FollowYourEmoji/infer.py", line 228, in <module>
    main(args, config)
  File "/opt/tiger/tools/sd/follow_emoji/FollowYourEmoji/infer.py", line 127, in main
    image_encoder = CLIPVisionModelWithProjection.from_pretrained(config.image_encoder_path).to(dtype=weight_dtype, device="cuda")
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3128, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/utils/hub.py", line 425, in cached_file
    raise EnvironmentError(
OSError: sd-image-variations-diffusers/image_encoder is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
`

**Comment by mayuelala** [comment]
you can download the weight from huggingface and put them in right path
